# Generated by Django 4.0.5 on 2022-08-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='movie_image',
            field=models.ImageField(null=True, upload_to='movie_images'),
        ),
    ]
